version: "3"

services:
  db:
    image: postgres:13-alpine
    ports:
      - 5432:5432
    volumes:
      - devduo:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  api:
    build: .
    image: go-devduo:0.1
    ports:
      - 8000:8000
    restart: on-failure:10
    depends_on:
      - db
volumes:
  devduo:
